# Simple docker-compose.yml already available in @[louislam](https://github.com/louislam) 's [Repo](https://github.com/louislam/uptime-kuma/blob/master/docker/docker-compose.yml) 
# You can change your port or volume location

version: '3.3'

services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    volumes:
      - ./uptime-kuma-data:/app/data
    ports:
      - 3001:3001  # <Host Port>:<Container Port>
    restart: always
